apiVersion: v1
data:
  rules.yaml: |
    - selector:
        app: http-app
      annotations:
        log.config.scalyr.com/include: true
kind: ConfigMap
metadata:
  labels:
    app: kube-annotate
  name: kube-annotate-config
