apiVersion: v1
kind: Service
metadata:
  labels:
    app: kube-annotate
  name: kube-annotate
spec:
  type: ClusterIP
  ports:
  - name: https
    port: 443
    targetPort: https
  selector:
    app: kube-annotate

